![pic](https://i.pinimg.com/736x/0b/9f/24/0b9f24eaabab2631ce601bcf5f201d8f.jpg)

**Goal:**

> Dataset & DataLoader Class uses

- **Lecture 6:** https://youtu.be/RH6DeE3bY6I?si=ENjMCbQrTSvnFS7W
- **My PyTroch Repo:** https://github.com/Rudra-G-23/deep-learning-using-pytorch

In [23]:
import torch 
from torch.utils.data import Dataset, DataLoader
from sklearn.datasets import make_classification

# Dataset

In [24]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

print(X.shape)
print(y.shape)

(10, 2)
(10,)


# Numpy to tensor

In [25]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [38]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [39]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

# Custom dataset class

In [31]:
class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [32]:
# create an instance 
dataset = CustomDataset(X, y)

In [33]:
# check the length
len(dataset)

10

# DatasetLoader

In [34]:
# batch_size is the idx at the top, and shuffle is a random row number 
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [37]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print('-'*50)

tensor([[ 1.7774,  1.5116],
        [ 1.7273, -1.1858]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.8997,  0.8344]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-1.9629, -0.9923]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [-2.8954,  1.9769]])
tensor([0, 0])
--------------------------------------------------
