![pic](https://i.pinimg.com/736x/0b/9f/24/0b9f24eaabab2631ce601bcf5f201d8f.jpg)

**Goal**

> Enhance the training pipeline using the dataset and data loader

- **Lecture 6:** https://youtu.be/RH6DeE3bY6I?si=Gh9EXYojuITmKv8J
- **My PyTroch Repo:** https://github.com/Rudra-G-23/deep-learning-using-pytorch

# Deep Learning using PyTorch 

|No | Topic | My Notebook | Lectures |
|---| -------- | ----------- | ------------ |
| 01 | PyTorch for Beginners | [🗺️](https://github.com/Rudra-G-23/AI-Engineering-Resources/tree/main/PyTorch) | [🧑‍🏫](https://youtu.be/QZsguRbcOBM?si=xS9S0YBpN4AtVNiA) |
| 02 | Tensor in PyTorch | [📒](https://www.kaggle.com/code/rudraprasadbhuyan/tensors-in-pytorch/) | [🧑‍🏫](https://youtu.be/mDsFsnw3SK4?si=7UXsevk1lyPfcM9B)|
| 03 |PyTorch Autograd | [📒](https://www.kaggle.com/code/rudraprasadbhuyan/pytorch-autograd/) | [🧑‍🏫](https://youtu.be/BECZ0UB5AR0?si=fnEYItyybv5nky2y) |
| 04 |PyTorch Training Pipeline | [📒](https://www.kaggle.com/code/rudraprasadbhuyan/simple-pytorch-training-pipeline/) | [🧑‍🏫](https://youtu.be/MKxEbbKpL5Q?si=xrUovfzRyXfvmM8E) |
| 05 | PyTorch NN Module | [1📒](https://www.kaggle.com/code/rudraprasadbhuyan/simple-pytorch-nn-module?scriptVersionId=289809301), [2📒](https://www.kaggle.com/code/rudraprasadbhuyan/pytorch-training-pipeline-using-nn-module?scriptVersionId=289814480) | [🧑‍🏫](https://youtu.be/CAgWNxlmYsc?si=INKJ8VcdQgcYwxAe) |
|06 |Dataset & DataLoader Class | [1📒](https://www.kaggle.com/code/rudraprasadbhuyan/dataset-and-dataloader-class-in-pytorch), [2📒](https://www.kaggle.com/code/rudraprasadbhuyan/pytorch-training-pipeline-using-dataset-dataloader/) | [🧑‍🏫](https://youtu.be/RH6DeE3bY6I?si=ac6IsukunPNN_dC9) |


In [33]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

import warnings
warnings.filterwarnings('ignore')

# Dataset

In [34]:
path = "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
df = pd.read_csv(path)
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [35]:
df.shape

(569, 33)

In [36]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [37]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, 1:],
    df.iloc[:, 0],
    test_size=0.2
)

# Scaling

In [39]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [40]:
X_train

array([[-0.86186049, -0.99898821, -0.83484654, ..., -0.0967095 ,
         0.63833122,  0.38338349],
       [-0.46336306,  1.11034145, -0.31869345, ...,  1.61308226,
         2.31120485,  6.59978182],
       [ 1.83938283,  0.37161146,  1.90763035, ...,  1.51968395,
         0.28647799, -0.42149893],
       ...,
       [-0.10186896,  0.77814526,  0.07958815, ...,  1.61006941,
         1.10170936,  3.16931008],
       [-0.34096742, -0.82708249, -0.31414402, ..., -0.18408212,
        -1.40681569, -0.65694435],
       [-0.65122613, -0.46468664, -0.67892529, ..., -0.90927486,
        -0.18161247, -0.1274585 ]])

In [41]:
y_train

342    B
9      M
535    M
426    B
183    B
      ..
89     B
542    B
14     M
284    B
399    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [42]:
encoder = LabelEncoder()
# Convert both to a string to ensure consistency
y_train = encoder.fit_transform(y_train.astype(str))
y_test = encoder.transform(y_test.astype(str))

# Numpy arrays to PyTorch tnesors

In [43]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [44]:
X_train_tensor.shape

torch.Size([455, 30])

In [45]:
y_train_tensor.shape

torch.Size([455])

# Dataset

In [46]:
class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [47]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [48]:
train_dataset[0]

(tensor([-0.8619, -0.9990, -0.8348, -0.7871,  0.5149, -0.2322, -0.4361, -0.3874,
         -0.1192,  0.9040, -0.8606, -0.7366, -0.7331, -0.6219,  0.1222, -0.3738,
         -0.1503, -0.2656,  0.3506, -0.3185, -0.8929, -0.9526, -0.8132, -0.7655,
          0.4287, -0.2038, -0.2033, -0.0967,  0.6383,  0.3834]),
 tensor(0.))

# Data loader

In [49]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Defining the Model (using NN Module)

All steps included the nn model 
-> Using the nn module

- First, we create a class
- Weights, bias 
- Then create the functions 
    -  Forward calculation
    -  Loss find 
    -  Update the Weights


In [50]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        # Perceptron design
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        # Update the values
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

# Imp Parameters

**Loss**

$$\mathcal{L} = - \Big[ y_{\text{target}} \log(y_{\text{pred}}) + (1 - y_{\text{target}}) \log(1 - y_{\text{pred}}) \Big]$$

In [51]:
LR = 0.1
EPOCHS = 25

# No need for manually finding the loss function
loss_function = nn.BCELoss()

# Training Pipeline

In [52]:
#  Inside the training pipeline
# In a loop

# define a loop
    # forward pass
    # loss calculate
    # clear gradients
    # backwrad pass
    # parameters update
    # print the loss in each epoch


In [53]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define the optimiser 
optimizer = torch.optim.SGD(model.parameters(), lr=LR)

# define a loop
for epoch in range(EPOCHS):
    
    # forward pass
    y_pred = model(X_train_tensor)
    
    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
    
    # clear gradients
    optimizer.zero_grad()
    
    # backwrad pass
    loss.backward()
    
    # parameters update
    optimizer.step()
    
    # print the loss in each epoch
    print(f"Epoch: {epoch + 1} | Loss: {loss.item()} ")

Epoch: 1 | Loss: 0.5060296654701233 
Epoch: 2 | Loss: 0.4321819543838501 
Epoch: 3 | Loss: 0.3837607502937317 
Epoch: 4 | Loss: 0.34906676411628723 
Epoch: 5 | Loss: 0.3226969838142395 
Epoch: 6 | Loss: 0.3018014132976532 
Epoch: 7 | Loss: 0.28472477197647095 
Epoch: 8 | Loss: 0.2704349756240845 
Epoch: 9 | Loss: 0.2582521140575409 
Epoch: 10 | Loss: 0.24770842492580414 
Epoch: 11 | Loss: 0.23847009241580963 
Epoch: 12 | Loss: 0.23029190301895142 
Epoch: 13 | Loss: 0.22298896312713623 
Epoch: 14 | Loss: 0.21641883254051208 
Epoch: 15 | Loss: 0.2104697823524475 
Epoch: 16 | Loss: 0.20505250990390778 
Epoch: 17 | Loss: 0.20009474456310272 
Epoch: 18 | Loss: 0.19553734362125397 
Epoch: 19 | Loss: 0.19133110344409943 
Epoch: 20 | Loss: 0.1874348670244217 
Epoch: 21 | Loss: 0.1838139146566391 
Epoch: 22 | Loss: 0.1804385632276535 
Epoch: 23 | Loss: 0.17728345096111298 
Epoch: 24 | Loss: 0.1743265986442566 
Epoch: 25 | Loss: 0.1715489625930786 


# Model bias and weights

In [54]:
model.linear.bias

Parameter containing:
tensor([-0.2952], requires_grad=True)

In [55]:
model.linear.weight

Parameter containing:
tensor([[ 0.1611,  0.1176,  0.3515,  0.3467,  0.1966,  0.0743,  0.2274,  0.1393,
          0.1452,  0.0655,  0.0743, -0.0489,  0.0412,  0.3136,  0.1254, -0.0879,
         -0.0006,  0.1073, -0.1804, -0.0664,  0.2015,  0.1338,  0.3589,  0.3846,
          0.1804,  0.2179,  0.1251,  0.1956,  0.2675,  0.0081]],
       requires_grad=True)

# Evaluation

In [56]:
# set the model to evaluation mode
model.eval()

MySimpleNN(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

## Train accuracy 

In [58]:
# Model evaluation using test_loader
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in train_loader:

        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()

        # calculate the accuracy
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accurac: {overall_accuracy:.4f} ")

Accurac: 0.9646 


## Test accuracy 

In [57]:
# Model evaluation using test_loader
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:

        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()

        # calculate the accuracy
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accurac: {overall_accuracy:.4f} ")

Accurac: 0.9646 
