![pic](https://i.pinimg.com/736x/98/6b/2d/986b2dde1220395ae846c6ada8a524c7.jpg)

**Goal**

> - Same as the [previous notebook](https://www.kaggle.com/code/rudraprasadbhuyan/simple-pytorch-training-pipeline), but here we used the nn module
> - The previous notebook we did manually
> - https://www.kaggle.com/code/rudraprasadbhuyan/simple-pytorch-training-pipeline

- **Lecture 5:** https://youtu.be/CAgWNxlmYsc?si=Ybow1K6A27mGHJAq
- **My PyTroch Repo:** https://github.com/Rudra-G-23/deep-learning-using-pytorch

In [41]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

import warnings
warnings.filterwarnings('ignore')

# Dataset

In [42]:
path = "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
df = pd.read_csv(path)
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [43]:
df.shape

(569, 33)

In [44]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [45]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, 1:],
    df.iloc[:, 0],
    test_size=0.2
)

# Scaling

In [47]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [48]:
X_train

array([[-1.26468386, -1.42738625, -1.14892586, ..., -0.10823508,
        -0.08742215,  2.86754393],
       [ 0.00852996,  1.06990955,  0.02886205, ...,  0.9479969 ,
         2.86112383,  1.02077412],
       [ 1.06343019,  1.22672194,  0.9436448 , ..., -0.01579584,
        -0.6280937 , -0.24246014],
       ...,
       [-0.03942005, -0.83758443, -0.10550819, ..., -0.49223677,
        -1.20648651, -0.91888056],
       [ 1.5937009 ,  0.68138931,  1.54994953, ...,  1.88148168,
        -0.21315972, -0.42440521],
       [ 2.21423045,  0.62287722,  2.25457395, ...,  1.94815917,
        -0.25559615,  0.09957474]])

In [49]:
y_train

505    B
214    M
274    M
387    B
69     B
      ..
87     M
548    B
439    B
18     M
369    M
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [50]:
encoder = LabelEncoder()
# Convert both to a string to ensure consistency
y_train = encoder.fit_transform(y_train.astype(str))
y_test = encoder.transform(y_test.astype(str))

# Numpy arrays to PyTorch tnesors

In [74]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [75]:
X_train_tensor.shape

torch.Size([455, 30])

In [76]:
y_train_tensor.shape

torch.Size([455])

# Defining the Model (using NN Module)

All steps included the nn model 
-> Using the nn module

- First, we create a class
- Weights, bias 
- Then create the functions 
    -  Forward calculation
    -  Loss find 
    -  Update the Weights


In [77]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        # Perceptron design
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        # Update the values
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

# Imp Parameters

**Loss**

$$\mathcal{L} = - \Big[ y_{\text{target}} \log(y_{\text{pred}}) + (1 - y_{\text{target}}) \log(1 - y_{\text{pred}}) \Big]$$

In [78]:
LR = 0.1
EPOCHS = 25

# No need for manually finding the loss function
loss_function = nn.BCELoss()

# Training Pipeline

In [79]:
#  Inside the training pipeline
# In a loop

# define a loop
    # forward pass
    # loss calculate
    # clear gradients
    # backwrad pass
    # parameters update
    # print the loss in each epoch


In [80]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define the optimiser 
optimizer = torch.optim.SGD(model.parameters(), lr=LR)

# define a loop
for epoch in range(EPOCHS):
    
    # forward pass
    y_pred = model(X_train_tensor)
    
    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
    
    # clear gradients
    optimizer.zero_grad()
    
    # backwrad pass
    loss.backward()
    
    # parameters update
    optimizer.step()
    
    # print the loss in each epoch
    print(f"Epoch: {epoch + 1} | Loss: {loss.item()} ")

Epoch: 1 | Loss: 0.785175085067749 
Epoch: 2 | Loss: 0.5974287390708923 
Epoch: 3 | Loss: 0.48983100056648254 
Epoch: 4 | Loss: 0.4218887388706207 
Epoch: 5 | Loss: 0.3752851188182831 
Epoch: 6 | Loss: 0.34123262763023376 
Epoch: 7 | Loss: 0.31511610746383667 
Epoch: 8 | Loss: 0.2943187952041626 
Epoch: 9 | Loss: 0.27726075053215027 
Epoch: 10 | Loss: 0.26293665170669556 
Epoch: 11 | Loss: 0.25067803263664246 
Epoch: 12 | Loss: 0.2400234192609787 
Epoch: 13 | Loss: 0.23064370453357697 
Epoch: 14 | Loss: 0.2222977727651596 
Epoch: 15 | Loss: 0.21480469405651093 
Epoch: 16 | Loss: 0.208025723695755 
Epoch: 17 | Loss: 0.20185253024101257 
Epoch: 18 | Loss: 0.1961992383003235 
Epoch: 19 | Loss: 0.19099661707878113 
Epoch: 20 | Loss: 0.18618808686733246 
Epoch: 21 | Loss: 0.1817270666360855 
Epoch: 22 | Loss: 0.1775745451450348 
Epoch: 23 | Loss: 0.17369765043258667 
Epoch: 24 | Loss: 0.17006832361221313 
Epoch: 25 | Loss: 0.1666625589132309 


# Model bias and weights

In [81]:
model.linear.bias

Parameter containing:
tensor([-0.0355], requires_grad=True)

In [82]:
model.linear.weight

Parameter containing:
tensor([[ 0.3293,  0.0893,  0.3420,  0.2816,  0.1254,  0.0059,  0.3525,  0.3532,
         -0.0406,  0.0564,  0.2231,  0.1220,  0.1919,  0.3061,  0.0612, -0.0589,
          0.0296,  0.0749, -0.1182, -0.1528,  0.1177,  0.1160,  0.1803,  0.3052,
          0.1563,  0.0620,  0.2625,  0.2792,  0.1448, -0.0071]],
       requires_grad=True)

# Evaluation

In [85]:
# Model evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.5).float()

    accuracy = (y_pred.view(-1) == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.9210526347160339
