![pic](https://i.pinimg.com/736x/98/6b/2d/986b2dde1220395ae846c6ada8a524c7.jpg)

> In this module we learn how to use the NN Module in PyTroch


- **Lecture 5:** https://youtu.be/CAgWNxlmYsc?si=HUZG2zOKZCvIg-1Z
- **My PyTroch Repo:** https://github.com/Rudra-G-23/deep-learning-using-pytorch

In [4]:
!pip install torch torchinfo

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.5 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 96.0 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 73.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 44.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.0 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 8.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 30.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 12.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 8.1 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 54.1 MB/s eta 0:00:0000:0100:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed.

In [38]:
import torch
import torch.nn as nn
from torchinfo import summary

**Sequential/ Model Class**

    - First layer ( n_features, output=3)
    - 2nd layer ( 3 inputs and 1 output )
    - Means a perceptron 

In [39]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

Create a dataset 
    - 10 rows and 5 cols
    
Then create Model class instance with shape of dataset

In [40]:
# create dataset
features = torch.rand(10, 5)
print(features)

# create model
model = Model(features.shape[1])
model

tensor([[7.4680e-01, 2.7931e-04, 6.8231e-01, 8.4625e-01, 2.9849e-01],
        [8.4076e-01, 4.4448e-01, 4.1616e-01, 4.4155e-01, 1.3090e-01],
        [6.7037e-01, 5.5695e-01, 6.0554e-01, 2.5941e-01, 3.6534e-01],
        [9.3556e-01, 6.1402e-01, 9.7457e-01, 5.0830e-01, 2.8784e-01],
        [7.1057e-01, 7.9815e-01, 6.5869e-01, 7.1056e-01, 8.1209e-01],
        [5.2719e-01, 1.9227e-01, 9.4935e-01, 7.5472e-01, 7.7865e-01],
        [1.5837e-01, 1.1362e-01, 4.8934e-01, 5.7908e-01, 2.9213e-01],
        [3.4980e-01, 7.7592e-01, 6.6156e-01, 3.1094e-01, 2.5580e-01],
        [4.9182e-01, 9.5295e-01, 3.2525e-01, 7.4511e-01, 3.4828e-01],
        [7.5846e-01, 4.8523e-01, 8.6620e-01, 1.2301e-01, 7.5621e-01]])


Model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

In [41]:
# see the model summary
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       18
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [42]:
# call model for forward
model(features)

tensor([[0.6536],
        [0.6475],
        [0.6630],
        [0.6562],
        [0.6410],
        [0.6661],
        [0.6596],
        [0.6566],
        [0.6160],
        [0.6679]], grad_fn=<SigmoidBackward0>)

In [43]:
# show model weights
model.state_dict()

OrderedDict([('network.0.weight',
              tensor([[-0.0094,  0.2562, -0.0230,  0.3545, -0.2238],
                      [-0.2314,  0.3044,  0.0457,  0.4354,  0.2059],
                      [-0.1281,  0.2219,  0.2542,  0.1877,  0.2101]])),
             ('network.0.bias', tensor([-0.1317, -0.4061,  0.1556])),
             ('network.2.weight', tensor([[-0.4881, -0.5144,  0.2232]])),
             ('network.2.bias', tensor([0.5719]))])