![pic](https://i.pinimg.com/736x/83/48/ae/8348ae7e8bfe6a05b0c36ebff18a146e.jpg)

In [1]:
!pip install -q troch 

ERROR: Could not find a version that satisfies the requirement troch (from versions: none)
ERROR: No matching distribution found for troch


In [2]:
import torch
print(f"PyTorch Version: {torch.__version__}")
print(f"CUDA Available: {torch.cuda.is_available()}")

PyTorch Version: 2.8.0+cu126
CUDA Available: False


# Creating a Tensor

In [3]:
# Using empty
a = torch.empty(2, 3)
a

tensor([[5.4663e+22, 2.0971e-07, 1.6132e-07],
        [1.0027e-11, 1.7249e-07, 1.0812e-05]])

In [4]:
# Check Data type
type(a)

torch.Tensor

In [5]:
# Using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Using Ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# Using rand
torch.rand(2, 3)

tensor([[0.5282, 0.7454, 0.6128],
        [0.0249, 0.2524, 0.3992]])

In [8]:
# use of seed
torch.rand(2, 3)

tensor([[0.3839, 0.5176, 0.0744],
        [0.8664, 0.1283, 0.6897]])

In [9]:
# Use of seed
torch.rand(2, 3)

tensor([[0.8243, 0.8886, 0.0370],
        [0.3099, 0.7071, 0.6914]])

In [10]:
# Mannual_seed
# Now the random number is fixed because the seed is fixed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2, 3)

# See same matrix

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# Using tensor
torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# arrange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [16]:
# Linspace
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [17]:
# using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
torch.full((3, 4), 5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

# Tensor Shapes

In [23]:
x = torch.tensor([
    [1, 2, 3,],
    [4, 5, 6,]
])

x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
x.shape

torch.Size([2, 3])

In [25]:
torch.empty_like(x)

tensor([[136040126856592,       809175424,       812152368],
        [      817383712,               0,       817411520]])

In [27]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [29]:
# Find data types
x.dtype

torch.int64

In [31]:
# Assign data type
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [32]:
# give integer but show in float
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [36]:
x = torch.tensor([1, 2, 3,])
x

tensor([1, 2, 3])

In [37]:
# using to()
# Change this tensor into a float
x.to(torch.float)

tensor([1., 2., 3.])

# Mathematical Operations

## 1. Scalar Operation 

In [38]:
x = torch.rand(2, 3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [39]:
# addition
x + 2

tensor([[2.7118, 2.7876, 2.4183],
        [2.9014, 2.9969, 2.7565]])

In [40]:
# subtraction
x - 2

tensor([[-1.2882, -1.2124, -1.5817],
        [-1.0986, -1.0031, -1.2435]])

In [41]:
# Multiplication
x * 2

tensor([[1.4235, 1.5752, 0.8366],
        [1.8028, 1.9938, 1.5130]])

In [42]:
# division 
x / 3

tensor([[0.2373, 0.2625, 0.1394],
        [0.3005, 0.3323, 0.2522]])

In [43]:
# int division
(x * 100) // 3

tensor([[23., 26., 13.],
        [30., 33., 25.]])

In [44]:
# mod
( (x * 100) // 3 ) % 2

tensor([[1., 0., 1.],
        [0., 1., 1.]])

In [45]:
# power 
x ** 3

tensor([[0.3606, 0.4885, 0.0732],
        [0.7324, 0.9907, 0.4330]])

## 2. Element-wise operation 

In [47]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [48]:
# add 
a + b

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [49]:
# sub
a - b

tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])

In [50]:
# mul
a * b

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [51]:
# division
a / b 

tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [52]:
# power
a ** b

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

In [53]:
# mod 
a % b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [54]:
c = torch.tensor([1, 2, -3, 5, -6])
c

tensor([ 1,  2, -3,  5, -6])

In [55]:
torch.abs(c)

tensor([1, 2, 3, 5, 6])

In [56]:
# negative 
torch.neg(c)

tensor([-1, -2,  3, -5,  6])

In [57]:
d = torch.tensor([1.2, 3.8, 4, 5.6])
d

tensor([1.2000, 3.8000, 4.0000, 5.6000])

In [58]:
# round
torch.round(d)

tensor([1., 4., 4., 6.])

In [59]:
# ceil
torch.ceil(d)

tensor([2., 4., 4., 6.])

In [60]:
# Floor
torch.floor(d)

tensor([1., 3., 4., 5.])

In [61]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2., 3., 3., 3.])

## 3. Reduction Operation

In [66]:
e = torch.randint(
    size=(2, 3),
    low=0, 
    high=10,
    dtype=torch.float32
)

e

tensor([[5., 9., 9.],
        [7., 5., 9.]])

In [67]:
#sum
torch.sum(e)

tensor(44.)

In [68]:
# sum along columns
torch.sum(e, dim=0)

tensor([12., 14., 18.])

In [69]:
# sum along rows
torch.sum(e, dim=1)

tensor([23., 21.])

In [70]:
# mean
torch.mean(e)

tensor(7.3333)

In [72]:
# mean along col
torch.mean(e, dim=0)

tensor([6., 7., 9.])

In [73]:
# mean along rows
torch.mean(e, dim=1)

tensor([7.6667, 7.0000])

In [75]:
# median 
torch.median(e)

tensor(7.)

In [76]:
# min & max
torch.min(e)

tensor(5.)

In [77]:
torch.max(e)

tensor(9.)

In [79]:
e

tensor([[5., 9., 9.],
        [7., 5., 9.]])

In [78]:
torch.min(e, dim=0)

torch.return_types.min(
values=tensor([5., 5., 9.]),
indices=tensor([0, 1, 0]))

- This happens values, ideas
- for the first column, whose `value` is min
- `indices` indicate which column is min

In [80]:
mins, indxs = torch.min(e, dim=0)
print(mins)
print(indxs)

tensor([5., 5., 9.])
tensor([0, 1, 0])


In [83]:
# product
torch.prod(e)

tensor(127575.)

In [81]:
# global minimum 
torch.argmin(e)

tensor(0)

In [84]:
# standard deviation
torch.std(e)

tensor(1.9664)

In [85]:
# variance
torch.var(e)

tensor(3.8667)

## 4. Matrix Operation 

In [88]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[5, 5, 0],
        [4, 3, 8]])
tensor([[8, 3],
        [3, 5],
        [0, 6]])


In [89]:
# matrix multiplication
torch.matmul(f, g)

tensor([[55, 40],
        [41, 75]])

In [91]:
v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

In [92]:
# dot product
torch.dot(v1, v2)

tensor(11)

In [93]:
torch.transpose(f, 0, 1)

tensor([[5, 4],
        [5, 3],
        [0, 8]])

In [95]:
h = torch.randint(
    size=(3, 3),
    low=0,
    high=10,
    dtype=torch.float32
)

h

tensor([[4., 0., 8.],
        [4., 7., 2.],
        [3., 8., 5.]])

In [96]:
# determinant
torch.det(h)

tensor(164.)

In [97]:
# inverse
torch.inverse(h)

tensor([[ 0.1159,  0.3902, -0.3415],
        [-0.0854, -0.0244,  0.1463],
        [ 0.0671, -0.1951,  0.1707]])

## 5. Comparison Operations

In [100]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

In [101]:
# greater than
i > j

tensor([[ True, False, False],
        [ True, False,  True]])

In [102]:
# less than
i < j

tensor([[False,  True,  True],
        [False, False, False]])

In [103]:
# equl to 
i == j

tensor([[False, False, False],
        [False,  True, False]])

In [104]:
# not equal to 
i != j

tensor([[ True,  True,  True],
        [ True, False,  True]])

## 6. Special Functions

In [105]:
k = torch.randint(
    size=(2, 3),
    high=10
)

k

tensor([[6, 9, 2],
        [3, 1, 0]])

In [106]:
# log
torch.log(k)

tensor([[1.7918, 2.1972, 0.6931],
        [1.0986, 0.0000,   -inf]])

In [107]:
# exp
torch.exp(k)

tensor([[4.0343e+02, 8.1031e+03, 7.3891e+00],
        [2.0086e+01, 2.7183e+00, 1.0000e+00]])

In [108]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 3.0000, 1.4142],
        [1.7321, 1.0000, 0.0000]])

In [117]:
# softmax
torch.softmax(k.float(), dim=0)

tensor([[9.5257e-01, 9.9966e-01, 8.8080e-01],
        [4.7426e-02, 3.3535e-04, 1.1920e-01]])

In [110]:
# relu
torch.relu(k)

tensor([[6, 9, 2],
        [3, 1, 0]])

In [118]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9999, 0.8808],
        [0.9526, 0.7311, 0.5000]])

# Inplace Operations

In [119]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])
tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])


- We want to add these two number
- How to do without taking more memory space
- We calculate the sum then store in the `m` 

In [120]:
m + n

tensor([[1.4325, 0.9792, 0.9839],
        [1.1703, 1.8865, 1.2429]])

In [121]:
id(m)

136035512233296

In [122]:
id(n)

136035512224896

In [123]:
id(m + n)

136035514049120

- If we noticed all the memory locations
- All are different

In [124]:
m.add_(n)

tensor([[1.4325, 0.9792, 0.9839],
        [1.1703, 1.8865, 1.2429]])

In [125]:
m

tensor([[1.4325, 0.9792, 0.9839],
        [1.1703, 1.8865, 1.2429]])

In [126]:
id(m)

136035512233296

- Now, if we check the `m`
- The value of m is changed
- but the same memory location

In [127]:
torch.relu(m)

tensor([[1.4325, 0.9792, 0.9839],
        [1.1703, 1.8865, 1.2429]])

- `relu` creates a new memory location
- `relu_` calculate the value and update the variables
- In this way, we save the memory 

In [128]:
m.relu_()

tensor([[1.4325, 0.9792, 0.9839],
        [1.1703, 1.8865, 1.2429]])

In [129]:
m

tensor([[1.4325, 0.9792, 0.9839],
        [1.1703, 1.8865, 1.2429]])

In [130]:
id(m)

136035512233296

- Consistent memory location of `m` variable

# Coping a Tensor

In [131]:
a = torch.rand(2, 3)
a

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [132]:
# this is a copy 
b = a

In [133]:
a[0][0] = 0

- If we notice first, we copy the `a`
- That means we indicate the same memory location
- So when we change the [0,0] position in the matrix
- It also reflects on the `b` matrix as well

In [137]:
print(id(a))
a

136035512237536


tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [138]:
print(id(b))
b

136035512237536


tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

- We need a variable that does not change
- We still have our old value when the changes are going on
- So we perform the `conle` function to achieve this

In [139]:
c = torch.clone(a)

In [140]:
c

tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [141]:
a[0][0] = 10

- Now, if we notice the value and memory location
- Of both `a` and `c`, then we see the difference clearly 

In [142]:
print(id(a))
a

tensor([[10.0000,  0.2651,  0.2336],
        [ 0.5057,  0.5688,  0.0634]])

In [144]:
print(id(c))
c

136035512271088


tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])